version: '3'

tasks:
  default:
    silent: true
    cmds:
    - task --list

  init:
    cmds:
      - true

  install:
    desc: prepare instance with Ansible playbooks
    cmds:
    - |
      pkgx +gnu.org/coreutils env \
           --split-string \
           --ignore-environment \
           REMOTE_FQDN="${REMOTE_FQDN}" \
           REMOTE_USER="${REMOTE_USER}" \
           USER="${USER}" \
           HOME="${HOME}" \
           PATH="${HOME}/.pkgx/bin:/bin:/usr/bin:/usr/local/bin" \
           pkgx +gnu.org/bash^5 bash \
                --login \
                --noprofile \
                --norc \
                - <<'EOF'
                  eval "$(pkgx --shellcode)"
                  eval "$(ssh-agent)" 2>&1 > /dev/null
                  ssh-add -q "{{.CONSTRUCTOR_SSH_KEY_PATH}}" 2>&1 > /dev/null
                  export ANSIBLE_SSH_USER="{{.REMOTE_USER}}"
                  export HUB_PERSISTENT_VOLUME_PATH="{{.HUB_PERSISTENT_VOLUME_PATH}}"
                  export JUPYTERHUB_FQDN="{{.JUPYTERHUB_FQDN}}"
                  export FILESERVER_EXPORT_PATH="{{.FILESERVER_EXPORT_PATH}}"
                  export INVENTORY="${PWD}/inventory-ansible.pkgx"
                  export ANSIBLE_ROLES_PATH="${PWD}/roles"
                  ansible-playbook \
                      --inventory "${INVENTORY}" \
                      "${PWD}/playbooks/main.yaml"
      EOF